### ISSUE TITLE
iProtector conflinct

### ISSUE THREAD

**Issue by NycuRO** [jjplaying/Worlds#10] opened 2016-11-28 14:34 UTC
If you use iProtector plugin ,area pos1 pos2 with god flag not work on plugin..

You can fix? I need area pos1 pos2 god.. for spawn

**Comment by jjplaying** [comment] 2016-11-28 16:41
Do you mean that I shouldn't use those commands because they're already used by iProtector?

**Comment by NycuRO** [comment] 2016-11-28 16:48
Yes. I need to disable pvp in my island ( SkyPvP ) and in other enable. For this i need pos1 pos2 ..

**Comment by jjplaying** [comment] 2016-11-28 17:48
So this is a duplicate of #9.

**Closed by jjplaying** 2016-11-28 17:48 UTC

**Comment by jarne** [comment] 2017-04-18 10:38
Now I unterstand your issue, it has been fixed with #15.

**Comment by NycuRO** [comment] 2017-04-18 12:52
wow, nov 2016.....

**Comment by jarne** [comment] 2017-04-18 17:47
Sorry, I didn't worked on those plugins for a few months because I were busy with other things.
